log_file:
database:
mni_template:
raw:

padded_image:
mni_registered_image:
bias_corrected_image:
normalized_image:
preprocessed_image:

padded_label:
mni_registered_label:
imputed_label:
corrected_label:
preprocessed_label:

unet:
  train:
  validation:
  test:
  checkpoint:
  train_config:
  test_config:
